### Introductions to Tensors

In [2]:
import torch

In [3]:
# Creating 0 Dimentional Data
scalar_data = torch.tensor(4)
print(f"Scalar Data Points: {scalar_data}")

Scalar Data Points: 4


In [7]:
# Creating 1 Dimentional Data Called Vector
vector_data = torch.tensor([1, 2, 3])
print(f"Vector Data Points: \n{vector_data}")

Vector Data Points: 
tensor([1, 2, 3])


In [6]:
# Creating 2 Dimentional Data Called Matrix
matrix_data = torch.tensor([[1, 2, 3],
                            [4, 5, 6]])
print(f"Matirx Data Points: \n{matrix_data}")

Matirx Data Points: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [8]:
# Creating Multi Dimentional Data Called Tensor
tensor_data = torch.tensor([[[1, 2, 3],
                            [4, 5, 6]], 
                            [[1, 2, 3], [7, 8, 9]]])
print(f"Tensor Data Points: \n{tensor_data}")

Tensor Data Points: 
tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [7, 8, 9]]])


### Manipulate The Tensor Data 

In [9]:
# Creating 0 Dimentional Data
scalar_data = torch.tensor(4, 2)
print(f"Scalar Data Points: {scalar_data}")

TypeError: tensor() takes 1 positional argument but 2 were given

### Creating a new shapes tensor with 0 value

In [11]:
# Creating a new shapes tensor with 0 value
scalar_data = torch.zeros(4, 2) # (Row , Column)
print(f"Scalar Data Points: \n{scalar_data}")

Scalar Data Points: 
tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


### Creating a new shapes tensor with 1 value

In [12]:
# Creating a new shapes tensor with 1 value
scalar_data = torch.ones(4, 2) # (Row , Column)
print(f"Scalar Data Points: \n{scalar_data}")

Scalar Data Points: 
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


### Creating a new shapes tensor with random value

In [13]:
# Creating a new shapes tensor with random value
scalar_data = torch.rand(4, 2) # (Row , Column)
print(f"Scalar Data Points: \n{scalar_data}")

Scalar Data Points: 
tensor([[0.6990, 0.0885],
        [0.3996, 0.8190],
        [0.3960, 0.4886],
        [0.4186, 0.4839]])


In [14]:
# Creating a new shapes tensor with random value
scalar_data = torch.rand(4, 2) # (Row , Column)
print(f"Scalar Data Points: \n{scalar_data}")

Scalar Data Points: 
tensor([[0.9464, 0.5499],
        [0.2402, 0.0534],
        [0.8821, 0.9450],
        [0.3887, 0.9854]])


### Find out the total number of elements in Tensor

In [19]:
# Creating a new shapes tensor with random value
scalar_data = torch.rand(4, 4) # (Row , Column)
print(f"Scalar Data Points: \n{scalar_data}")
print(f"\nShape of the random generated tensor: {scalar_data.shape}")
print(f"Total Number of elements in Tensor: {scalar_data.numel()}")

Scalar Data Points: 
tensor([[0.2202, 0.1945, 0.0445, 0.0577],
        [0.4244, 0.4581, 0.3506, 0.4439],
        [0.3591, 0.2826, 0.2323, 0.2031],
        [0.7264, 0.0213, 0.2623, 0.8033]])

Shape of the random generated tensor: torch.Size([4, 4])
Total Number of elements in Tensor: 16


### Reshape the Tensor Values

In [21]:
# Creating a new shapes tensor with random value
scalar_data = torch.rand(4, 2) # (Row , Column)\
print("---------------before Reshape-----------------")
print(f"Scalar Data Points: \n{scalar_data}")
print("---------------After Reshape-----------------")
scalar_data = scalar_data.view(2, 4)
print(f"Scalar Data Points After Reshape: \n{scalar_data}")

---------------before Reshape-----------------
Scalar Data Points: 
tensor([[0.6056, 0.8908],
        [0.0488, 0.3352],
        [0.6483, 0.6314],
        [0.6118, 0.2253]])
---------------After Reshape-----------------
Scalar Data Points After Reshape: 
tensor([[0.6056, 0.8908, 0.0488, 0.3352],
        [0.6483, 0.6314, 0.6118, 0.2253]])


### Slice the Tensor Values

In [22]:
# Creating a new shapes tensor with random value
scalar_data = torch.rand(4, 2) # (Row , Column)\
print("---------------before Slice-----------------")
print(f"Scalar Data Points: \n{scalar_data}")
print("---------------After Slice-----------------")
scalar_data = scalar_data[0, 1:3]
print(f"Scalar Data Points After Slice: \n{scalar_data}")

---------------before Slice-----------------
Scalar Data Points: 
tensor([[0.0869, 0.9113],
        [0.1998, 0.1746],
        [0.9621, 0.8479],
        [0.2662, 0.8936]])
---------------After Slice-----------------
Scalar Data Points After Slice: 
tensor([0.9113])


## <center>Home Work - 01</center>
### Find out the 6th Value of the Tensor using the slice method
```python
scalar_data = torch.rand(4, 2) # (Row , Column)\
print("---------------before Slice-----------------")
print(f"Scalar Data Points: \n{scalar_data}")
print("---------------After Slice-----------------")
scalar_data = scalar_data[0, 1:3]
print(f"Scalar Data Points After Slice: \n{scalar_data}")
```

<center><h3> Tensor Operations</h3></center>

In [24]:
# Taking the Tensor Values
tensor_value_01 = torch.tensor([[1, 2], [3, 4]])
tensor_value_02 = torch.tensor([[3, 4], [1, 2]])

### 01. Tensor Addition

In [25]:
addition = tensor_value_01  + tensor_value_02
print(f"Tensor Addition Result: \n{addition}")

Tensor Addition Result: 
tensor([[4, 6],
        [4, 6]])


In [29]:
multiplication = tensor_value_01  * tensor_value_02
print(f"Tensor Multiplication Result: \n{multiplication}")

Tensor Multiplication Result: 
tensor([[3, 8],
        [3, 8]])


In [27]:
divition = tensor_value_01  / tensor_value_02
print(f"Tensor Divition Result: \n{divition}")

Tensor Divition Result: 
tensor([[0.3333, 0.5000],
        [3.0000, 2.0000]])


In [28]:
multiplication = torch.mm(tensor_value_01, tensor_value_02)
print(f"Tensor Multiplication Result: \n{multiplication}")

Tensor Multiplication Result: 
tensor([[ 5,  8],
        [13, 20]])


In [30]:
transpose = torch.t(tensor_value_01)
print(f"Tensor Transpose Result: \n{transpose}")

Tensor Transpose Result: 
tensor([[1, 3],
        [2, 4]])


<center><h3>Broadcasting </h3></center>

In [32]:
# Broadcast
tensor_value_01 = torch.tensor([[1, 2], [3, 4]])
scalar = 5
addition_with_broadcast = tensor_value_01 + scalar
print(f"Broadcast Result: \n{addition_with_broadcast}")

Broadcast Result: 
tensor([[6, 7],
        [8, 9]])


<center><h3>GPU Acceleration</h3></center>

In [34]:
tensor_value_01 = torch.tensor([[1, 2], [3, 4]])
if torch.cuda.is_available():
    device = torch.device("cuda")
    calculation_on_gpu = tensor_value_01.to(device)
    print("Calculations Starting With GPU Accelerations")
    print(calculation_on_gpu)
else:
    print("GPU is not available")

Calculations Starting With GPU Accelerations
tensor([[1, 2],
        [3, 4]], device='cuda:0')


<center><h3>Pattern Convet Between Numpy and Pytorch</h3></center>

In [35]:
#Step 01: Creating Numpy array 
import numpy as np
array_01 = np.array([1, 2, 3])
torch_array = torch.from_numpy(array_01)
print(f"Before the Conversion The array is :\n{array_01}")
print(f"\nAfter the Conversion the array from Numpy to torch: \n{torch_array}")

Before the Conversion The array is :
[1 2 3]

After the Conversion the array from Numpy to torch: 
tensor([1, 2, 3], dtype=torch.int32)


In [36]:
#Step 01: Creating Numpy array 
import numpy as np
array_01 = torch.tensor([1, 2, 3])
torch_array = array_01.numpy()
print(f"Before the Conversion The array is :\n{array_01}")
print(f"\nAfter the Conversion the array from  torch to Numpy: \n{torch_array}")

Before the Conversion The array is :
tensor([1, 2, 3])

After the Conversion the array from  torch to Numpy: 
[1 2 3]


<center><h3>Saveing Pytorch Value </h3></center>

In [37]:
torch.save(tensor_value_01, "TensorValue.pt")

In [38]:
# Load the saved file form the local folder
load_tensor_value =torch.load("TensorValue.pt")
print(f"Loaded Tensor Data: \n{load_tensor_value}")

Loaded Tensor Data: 
tensor([[1, 2],
        [3, 4]])
